# PR Labeler Configuration
# Automatically applies labels to PRs based on changed files

# Frontend changes
frontend:
  - 'src/**'
  - 'public/**'
  - '*.html'
  - '*.css'
  - '*.scss'

# Component changes
components:
  - 'src/components/**'
  - 'src/stories/**'

# Hook changes
hooks:
  - 'src/hooks/**'

# Library/utility changes
lib:
  - 'src/lib/**'

# Type definitions
types:
  - 'src/types.ts'
  - 'src/**/*.d.ts'
  - 'src/vite-env.d.ts'

# Testing changes
testing:
  - 'src/**/*.test.ts'
  - 'src/**/*.test.tsx'
  - 'src/**/*.spec.ts'
  - 'src/**/*.spec.tsx'
  - 'vitest.config.ts'
  - 'src/lib/test-utils.ts'

# Documentation changes
documentation:
  - '*.md'
  - 'docs/**'
  - 'src/stories/**/*.mdx'

# Configuration changes
config:
  - '*.json'
  - '*.js'
  - '*.ts'
  - '.github/**'
  - 'netlify.toml'
  - 'tailwind.config.js'
  - 'vite.config.ts'
  - 'tsconfig*.json'
  - 'eslint.config.js'
  - 'postcss.config.js'

# Database/Supabase changes
database:
  - 'supabase/**'

# CI/CD changes
ci:
  - '.github/workflows/**'
  - '.github/actions/**'

# Dependency changes
dependencies:
  - 'package.json'
  - 'package-lock.json'

# Build/tooling changes
build:
  - 'scripts/**'
  - 'vite.config.ts'
  - 'vitest.config.ts'
  - 'chromatic.config.json'

# Security changes
security:
  - '.github/workflows/compliance.yml'
  - 'supabase/apply-rls-policies.sql'
  - 'supabase/RLS_POLICIES.md'

# Performance changes
performance:
  - 'src/components/performance-monitoring-dashboard.tsx'
  - 'src/lib/github-api-monitoring.ts'
  - 'src/lib/supabase-monitoring.ts'
  - 'docs/PERFORMANCE_MONITORING.md'

# Social cards/metadata
social:
  - 'src/components/social-cards/**'
  - 'scripts/*social-cards*'
  - 'public/social.png'

# Storybook changes
storybook:
  - 'src/**/*.stories.ts'
  - 'src/**/*.stories.tsx'
  - 'src/stories/**'
  - '.storybook/**'
  - 'chromatic.config.json'