# Netlify configuration for main app deployment

[build]
  # Build command for main React app with social cards
  command = "npm run build:netlify"
  
  # Directory where Vite builds to
  publish = "dist"
  
  # Node.js version (required for Playwright)
  environment = { NODE_VERSION = "20" }

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Redirect rules for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables for build
[context.production.environment]
  NODE_ENV = "production"
  
[context.deploy-preview.environment]
  NODE_ENV = "development"
  
[context.branch-deploy.environment]
  NODE_ENV = "development"

# Main app deployment configuration