[build]
  publish = "dist"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

# Disable ALL Netlify post-processing to prevent MIME type issues
[build.processing]
  skip_processing = true

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = false

[build.processing.images]
  compress = false

[dev]
  command = "vite --port 5174"
  framework = "#custom"
  targetPort = 5174
  publish = "dist"
  autoLaunch = false
  envFiles = [".env", ".env.local"]

# Deploy contexts
[context.production.environment]
  # Production-specific env vars can go here

[context.deploy-preview.environment]
  # Deploy preview specific env vars
  CONTEXT = "deploy-preview"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions.inngest-prod]
  node_bundler = "esbuild"

[functions.inngest]
  node_bundler = "esbuild"

[functions.github-webhook]
  node_bundler = "esbuild"

# Specific API routes (these must come first)
[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health-check"
  status = 200
  force = true

[[redirects]]
  from = "/api/inngest"
  to = "/.netlify/functions/inngest-prod"
  status = 200
  force = true

[[redirects]]
  from = "/api/hello"
  to = "/.netlify/functions/hello"
  status = 200
  force = true

[[redirects]]
  from = "/api/github/webhook"
  to = "/.netlify/functions/github-webhook"
  status = 200
  force = true

[[redirects]]
  from = "/api/github/webhook-test"
  to = "/.netlify/functions/github-webhook-test"
  status = 200
  force = true

[[redirects]]
  from = "/api/github/webhook-status"
  to = "/.netlify/functions/github-webhook-status"
  status = 200
  force = true

[[redirects]]
  from = "/api/github/callback"
  to = "/.netlify/functions/github-callback"
  status = 200
  force = true

[[redirects]]
  from = "/api/queue-event"
  to = "/.netlify/functions/api-queue-event"
  status = 200
  force = true

[[redirects]]
  from = "/api/discover-repository"
  to = "/.netlify/functions/api-discover-repository-simple"
  status = 200
  force = true

[[redirects]]
  from = "/api/validate-repository"
  to = "/.netlify/functions/validate-repository"
  status = 200
  force = true

# Headers are now managed in public/_headers file to avoid conflicts

# Redirect rules for SPA behavior (exclude functions and API routes)  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Path = ["!/.netlify/functions/*", "!/api/*"]}

