name: Continue Agent Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Generate GitHub App token for authentication
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          
      # Run Continue Review with App token
      - name: Continue Review
        uses: continuedev/continue-review@f7dc7026aa08683924d57cd2b29ab6c2e742a7fe
        with:
          github-token: ${{ steps.app-token.outputs.token }}  # Use App token, not GITHUB_TOKEN