name: Continue Agent Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      # The Continue Review action now handles App authentication internally
      # No need to generate tokens here - the action does it automatically
      - name: Continue Review
        uses: bdougie/contributor.info/actions/continue-review@main
        with:
          # Required Continue configuration
          continue-api-key: ${{ secrets.CONTINUE_API_KEY }}
          continue-config: 'bdougie/code-reviewer'  # Your Continue assistant
          continue-org: 'bdougie'
          
          # GitHub token for fallback (always provided)
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
          # Optional: Use your own GitHub App (if not using embedded one)
          # app-id: ${{ secrets.APP_ID }}
          # app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
          
          # The action will automatically:
          # 1. Try to use embedded App credentials (if built with them)
          # 2. Try to use provided App credentials (if given)
          # 3. Fall back to github-token (comments as github-actions[bot])