name: 'Continue Agent Review'
description: 'Perform code review using Continue Agent on pull requests'
author: 'Continue'

inputs:
  continue-api-key:
    description: 'API key for Continue service'
    required: true
  github-token:
    description: 'GitHub token for API access (or App installation token)'
    required: true
  continue-org:
    description: 'Continue organization/username from Continue Hub'
    required: true
  continue-config:
    description: 'Continue assistant path (format: username/assistant-name)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Continue CLI
      shell: bash
      run: |
        echo "Installing Continue CLI..."
        npm install -g @continuedev/cli@latest || {
          echo "Warning: Could not install Continue CLI globally"
        }

    - name: Install action dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        echo "Installing action dependencies..."
        npm init -y
        npm install @actions/core @actions/github @actions/exec js-yaml glob
        npm install --save-dev @types/js-yaml @types/node typescript tsx

    - name: Run Continue Review
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        CONTINUE_API_KEY: ${{ inputs.continue-api-key }}
        CONTINUE_ORG: ${{ inputs.continue-org }}
        CONTINUE_CONFIG: ${{ inputs.continue-config }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_CONTINUE_API_KEY: ${{ inputs.continue-api-key }}
        INPUT_CONTINUE_ORG: ${{ inputs.continue-org }}
        INPUT_CONTINUE_CONFIG: ${{ inputs.continue-config }}
      run: |
        echo "Running Continue Review..."
        npx tsx index.ts

branding:
  icon: 'code'
  color: 'blue'