# Example: Basic Workflow (Legacy)
# This workflow uses standard GitHub token authentication
# Consider upgrading to secure-app-workflow.yml for better security

name: Continue Review Basic

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  review:
    name: AI Code Review
    runs-on: ubuntu-latest
    
    if: |
      github.event_name == 'pull_request' || 
      (github.event_name == 'issue_comment' && 
       contains(github.event.comment.body, '@continue-agent'))
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # Basic authentication using GITHUB_TOKEN
      # Note: Comments will appear as "github-actions[bot]"
      - name: Continue AI Review
        uses: bdougie/contributor.info/actions/continue-review@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          continue-api-key: ${{ secrets.CONTINUE_API_KEY }}
          continue-org: 'continuedev'
          continue-config: 'continuedev/review-bot'