# Fly.io configuration for GitHub Webhook Handler
app = "contributor-info-webhooks"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = 5

[build]

[env]
  NODE_ENV = "production"
  PORT = "8080"

# HTTP service configuration
[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "30s"
    timeout = "3s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false

# Scale configuration
[metrics]
  port = 8080
  path = "/metrics"

# Machine configuration (using new format)
[vm]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"