name: 'Continue Agent Review'
description: 'Perform code review using Continue Agent on pull requests'
author: 'Continue'

inputs:
  continue-api-key:
    description: 'API key for Continue service'
    required: true
  github-token:
    description: 'GitHub token for API access'
    required: true
  continue-org:
    description: 'Continue organization/username from Continue Hub'
    required: true
  continue-config:
    description: 'Continue assistant path (format: username/assistant-name)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Continue CLI
      shell: bash
      run: |
        npm install -g @continuedev/cli@latest
        echo "Continue CLI installed successfully"
        cn --version || echo "Continue CLI version check failed"

    - name: Setup Python for GitHub interaction
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      shell: bash
      run: |
        pip install PyGithub

    - name: Generate and Run Review
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        CONTINUE_API_KEY: ${{ inputs.continue-api-key }}
        CONTINUE_ORG: ${{ inputs.continue-org }}
        CONTINUE_CONFIG: ${{ inputs.continue-config }}
      run: |
        # Copy the review script to current directory
        SCRIPT_DIR="${{ github.action_path }}"
        cp "$SCRIPT_DIR/continue_review.py" ./continue_review.py || {
          echo "ERROR: continue_review.py not found in action directory"
          echo "Looking in: $SCRIPT_DIR"
          ls -la "$SCRIPT_DIR" || true
          exit 1
        }
        
        # Run the review script with GitHub context as environment variable
        GITHUB_CONTEXT='${{ toJson(github) }}' python3 ./continue_review.py

branding:
  icon: 'code'
  color: 'blue'