/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IWorkspaceIdIndexRouteImport } from './routes/i/$workspaceId/index'
import { Route as OwnerRepoIndexRouteImport } from './routes/$owner/$repo/index'

const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IWorkspaceIdIndexRoute = IWorkspaceIdIndexRouteImport.update({
  id: '/i/$workspaceId/',
  path: '/i/$workspaceId/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIndexRoute = OwnerRepoIndexRouteImport.update({
  id: '/$owner/$repo/',
  path: '/$owner/$repo/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/trending': typeof TrendingRoute
  '/$owner/$repo': typeof OwnerRepoIndexRoute
  '/i/$workspaceId': typeof IWorkspaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/trending': typeof TrendingRoute
  '/$owner/$repo': typeof OwnerRepoIndexRoute
  '/i/$workspaceId': typeof IWorkspaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/trending': typeof TrendingRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/i/$workspaceId/': typeof IWorkspaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/trending' | '/$owner/$repo' | '/i/$workspaceId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/trending' | '/$owner/$repo' | '/i/$workspaceId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/trending'
    | '/$owner/$repo/'
    | '/i/$workspaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TrendingRoute: typeof TrendingRoute
  OwnerRepoIndexRoute: typeof OwnerRepoIndexRoute
  IWorkspaceIdIndexRoute: typeof IWorkspaceIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$workspaceId/': {
      id: '/i/$workspaceId/'
      path: '/i/$workspaceId'
      fullPath: '/i/$workspaceId'
      preLoaderRoute: typeof IWorkspaceIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/': {
      id: '/$owner/$repo/'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo'
      preLoaderRoute: typeof OwnerRepoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TrendingRoute: TrendingRoute,
  OwnerRepoIndexRoute: OwnerRepoIndexRoute,
  IWorkspaceIdIndexRoute: IWorkspaceIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

// TanStack Start imports removed - spike evaluation complete
// These were auto-generated but reference deleted router.tsx and start.tsx files
