name: Build and Legacy Tests

# NOTE: This workflow is being replaced by ci-tests.yml
# TODO: Remove this file once ci-tests.yml is proven stable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Verify test configuration
      run: |
        echo "Checking vitest configuration..."
        test -f vitest.config.ts && echo "✓ Config file exists" || echo "✗ Config file missing"
        echo "Environment check:"
        echo "VITE_SUPABASE_URL is: ${VITE_SUPABASE_URL:-NOT SET}"
        echo "Note: Tests are configured to run without environment variables"
        echo "Tests that will run (first 20):"
        npx vitest list --config ./vitest.config.ts 2>/dev/null | head -20 || echo "Could not list tests"
      
    - name: Run tests with local Supabase defaults
      run: |
        echo "Running tests with local Supabase defaults..."
        timeout 3m npx vitest run --no-coverage --reporter=verbose || exit 1
      env:
        NODE_ENV: test
        VITEST: true
      
    - name: Type check
      run: npx tsc --noEmit
      
    - name: Build production bundle
      run: npx tsc -b && npx vite build

  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Add job timeout to prevent hanging
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    # Enhanced caching for faster CI runs
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
          ~/.cache/playwright
        key: playwright-browsers-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          playwright-browsers-${{ runner.os }}-
          playwright-browsers-
    
    - name: Cache Playwright test results
      uses: actions/cache@v4
      with:
        path: |
          test-results
          playwright-report
        key: playwright-results-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          playwright-results-${{ runner.os }}-
      
    - name: Build application
      run: npm run build
      env:
        VITE_SUPABASE_URL: http://localhost:54321
        VITE_SUPABASE_ANON_KEY: mock-anon-key
        VITE_GITHUB_TOKEN: mock-github-token
      
    - name: Install Playwright browsers
      run: npx playwright install chromium --with-deps
      
    - name: Run Playwright tests
      # Only run critical flows - other tests need updates
      run: npx playwright test e2e/critical-flows.spec.ts --reporter=list
      env:
        CI: true
      
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30