name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Verify test configuration
      run: |
        echo "Checking vitest configuration..."
        test -f vitest.config.ts && echo "✓ Config file exists" || echo "✗ Config file missing"
        echo "Environment check:"
        echo "VITE_SUPABASE_URL is: ${VITE_SUPABASE_URL:-NOT SET}"
        echo "Note: Tests are configured to run without environment variables"
        echo "Tests that will run (first 20):"
        npx vitest list --config ./vitest.config.ts 2>/dev/null | head -20 || echo "Could not list tests"
      
    - name: Run tests with local Supabase defaults
      run: |
        echo "Running tests with local Supabase defaults..."
        timeout 3m npx vitest run --no-coverage --reporter=verbose || exit 1
      env:
        NODE_ENV: test
        VITEST: true
      
    - name: Type check
      run: npx tsc --noEmit
      
    - name: Build production bundle
      run: npx tsc -b && npx vite build

  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Add job timeout to prevent hanging
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    # Build the application
    - name: Build application
      run: npm run build
      
    # Run integration tests instead of Playwright e2e tests
    - name: Run integration tests
      run: npm run test:integration
      
    # Run bundle size check (requires build to be done first)
    - name: Check bundle size
      run: npm run test:bundle
      continue-on-error: true  # Don't fail build on size warnings
      
    - name: Upload bundle report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: bundle-report
        path: bundle-report.json
        retention-days: 7