name: Claude Code Review

on:
  pull_request:
    types: [ready_for_review]
    # Only run on specific file changes
    paths:
      - "src/**/*.ts"
      - "src/**/*.tsx"
      - "src/**/*.js"
      - "src/**/*.jsx"
      - "package.json"
      - "tsconfig.json"
      - "vite.config.ts"

jobs:
  claude-review:
    # Optional: Filter by PR author
    # if: |
    #   github.event.pull_request.user.login == 'external-contributor' ||
    #   github.event.pull_request.user.login == 'new-developer' ||
    #   github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR'
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4)
          # model: "claude-opus-4-20250514"
          
          # Direct prompt for automated review (no @claude mention needed)
          direct_prompt: |
            Please perform a comprehensive code review of this pull request. Use the available tools to:
            
            1. Build and test the code to identify any compilation or runtime issues
            2. Run linting and type checking to catch potential problems
            3. Analyze the code changes for:
               - Code quality and best practices
               - Potential bugs or logic errors
               - Performance implications
               - Security vulnerabilities
               - Test coverage and quality
               - Accessibility concerns for UI components
               - Consistency with existing codebase patterns
            
            4. Search the codebase for similar patterns or potential impacts
            5. Verify that changes align with project conventions in CLAUDE.md
            
            Provide specific, actionable feedback with code examples where appropriate.
            Be constructive and educational in your suggestions.

          # Use sticky comments to make Claude reuse the same comment on subsequent pushes to the same PR
          use_sticky_comment: true
          
          # Optional: Customize review based on file types
          # direct_prompt: |
          #   Review this PR focusing on:
          #   - For TypeScript files: Type safety and proper interface usage
          #   - For API endpoints: Security, input validation, and error handling
          #   - For React components: Performance, accessibility, and best practices
          #   - For tests: Coverage, edge cases, and test quality
          
          # Optional: Different prompts for different authors
          # direct_prompt: |
          #   ${{ github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR' && 
          #   'Welcome! Please review this PR from a first-time contributor. Be encouraging and provide detailed explanations for any suggestions.' ||
          #   'Please provide a thorough code review focusing on our coding standards and best practices.' }}
          
          # Enable comprehensive tool calling for thorough code review
          allowed_tools: "Bash(npm run build),Bash(npm run lint),Bash(npm run typecheck),Bash(npm test),Bash(npm run test:*),Bash(npx tsc:*),Bash(node:*),Bash(git diff:*),Bash(git log:*),Bash(grep:*),Bash(rg:*),Bash(find:*),Bash(ls:*),Read,Grep,Glob,LS"
          
          # Optional: Skip review for certain conditions
          # if: |
          #   !contains(github.event.pull_request.title, '[skip-review]') &&
          #   !contains(github.event.pull_request.title, '[WIP]')

