name: AI Code Review
on:
  pull_request:
    types: [opened, ready_for_review]
  issue_comment:
    types: [created]
  workflow_dispatch: # Allow manual testing

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: continuedev/continue/actions/base-review@bdougie/continue-agent
        with:
          continue-api-key: ${{ secrets.CONTINUE_API_KEY }}