name: Continue Agent Code Review
on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
  issue_comment:
    types: [created]
  workflow_dispatch: # Allow manual testing

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  review:
    runs-on: ubuntu-latest
    # Run on PRs automatically, or when triggered by @continue-agent in comments
    if: |
      github.event_name == 'pull_request' || 
      (github.event_name == 'issue_comment' && 
       github.event.issue.pull_request && 
       contains(github.event.comment.body, '@continue-agent')) ||
      github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.CONTINUE_APP_ID }}
          private-key: ${{ secrets.CONTINUE_APP_PRIVATE_KEY }}
      
      # Use local action until Continue merges GitHub App token support
      - name: Run Continue Review
        uses: ./actions/continue-review
        with:
          continue-api-key: ${{ secrets.CONTINUE_API_KEY }}
          github-token: ${{ steps.app-token.outputs.token }}
          continue-org: 'bdougie'  # Your Continue Hub username
          continue-config: 'bdougie/assistant'  # Your assistant path