name: Continue Agent Code Review
on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
  issue_comment:
    types: [created]
  workflow_dispatch: # Allow manual testing

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  review:
    runs-on: ubuntu-latest
    # Only run on PRs and PR comments (not issue comments)
    if: |
      github.event_name == 'pull_request' || 
      (github.event_name == 'issue_comment' && github.event.issue.pull_request) ||
      github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.CONTINUE_APP_ID }}
          private-key: ${{ secrets.CONTINUE_APP_PRIVATE_KEY }}
      
      # Use local action until Continue merges GitHub App token support
      - name: Run Continue Review
        uses: ./.github/actions/continue-review
        with:
          continue-api-key: ${{ secrets.CONTINUE_API_KEY }}
          github-token: ${{ steps.app-token.outputs.token }}