name: Continue Agent Code Review (App Auth)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Step 1: Generate GitHub App token
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          
      # Step 2: Use the Continue Review action with App token
      - name: Continue Review
        uses: continuedev/continue-review@main  # or use specific SHA
        with:
          github-token: ${{ steps.app-token.outputs.token }}  # Use App token instead of GITHUB_TOKEN
          # Add other configuration parameters as needed
          # review-model: "gpt-4"  # optional
          # review-languages: "typescript,javascript"  # optional