name: Continue Agent Issue Triage
on:
  schedule:
    - cron: '0 * * * *' # Runs every hour to triage issues without labels
  issues:
    types: [opened, edited, reopened]
  issue_comment:
    types: [created] # Trigger on new comments to detect @continue-agent mentions
  workflow_dispatch: # Allow manual testing
    inputs:
      issue_number:
        description: 'Issue number to triage'
        required: true
        type: string
      dry_run:
        description: 'Run in dry-run mode (no changes applied)'
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  issues: write

jobs:
  triage:
    runs-on: ubuntu-latest
    # Only run on issues that need triage or when @continue-agent is mentioned
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issues' && 
       (github.event.action == 'opened' || 
        github.event.action == 'edited' ||
        contains(github.event.issue.labels.*.name, 'needs-triage'))) ||
      (github.event_name == 'issue_comment' && 
       !github.event.issue.pull_request &&
       contains(github.event.comment.body, '@continue-agent'))

    permissions:
      contents: read # Read code and rules for analysis
      issues: write # Label issues and post comments

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 1 # Shallow clone for rules access

      # Generate GitHub App token for authentication
      - name: Generate App Token
        id: app-token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v2.0.0
        with:
          app-id: ${{ vars.CONTINUE_APP_ID }}
          private-key: ${{ secrets.CONTINUE_APP_PRIVATE_KEY }}

      # Run Continue Triage with App authentication
      - name: Run Continue Triage
        uses: ./actions/continue-triage
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          continue-api-key: ${{ secrets.CONTINUE_API_KEY }}
          continue-org: 'continuedev' # Continue's organization
          continue-config: 'continuedev/review-bot' # Continue's review assistant (used for triage)
          issue-number: ${{ github.event.inputs.issue_number || github.event.issue.number }}
          dry-run: ${{ github.event.inputs.dry_run || 'false' }}
