name: Deploy GitHub Webhooks to Fly.io

on:
  push:
    branches:
      - main
    paths:
      - 'fly-github-webhooks/**'
      - '.github/workflows/deploy-github-webhooks.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    name: Deploy GitHub Webhook Handler
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy to Fly.io
        run: |
          cd fly-github-webhooks
          flyctl deploy --remote-only \
            -a contributor-info-webhooks \
            --config fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      
      - name: Check deployment health
        run: |
          echo "Waiting for deployment to be healthy..."
          sleep 30
          
          # Check health endpoint
          response=$(curl -s -o /dev/null -w "%{http_code}" https://contributor-info-webhooks.fly.dev/health)
          
          if [ "$response" = "200" ]; then
            echo "✅ Deployment is healthy"
            curl -s https://contributor-info-webhooks.fly.dev/health | jq .
          else
            echo "❌ Health check failed with status: $response"
            exit 1
          fi
      
      - name: Report metrics
        if: success()
        run: |
          echo "📊 Deployment metrics:"
          curl -s https://contributor-info-webhooks.fly.dev/metrics | jq .
      
      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: '❌ GitHub Webhook deployment to Fly.io failed. Check the [workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).'
            })