name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
# Cancel in-progress runs for the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Total timeout for the job
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      env:
        # Use mock values for build
        VITE_SUPABASE_URL: http://localhost:54321
        VITE_SUPABASE_ANON_KEY: mock-anon-key
        VITE_GITHUB_TOKEN: mock-github-token
        
    - name: Install Playwright browsers
      run: npx playwright install chromium --with-deps
      
    - name: Run E2E tests
      run: npm run test:e2e
      env:
        CI: true
        # Ensure proper environment for tests
        VITE_SUPABASE_URL: http://localhost:54321
        VITE_SUPABASE_ANON_KEY: mock-anon-key
        
    - name: Upload test artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: |
          playwright-report/
          test-results/
        retention-days: 7