name: Edge Functions Quality

on:
  pull_request:
    paths:
      - 'supabase/functions/**'
  push:
    branches:
      - main
    paths:
      - 'supabase/functions/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - name: Run linter
        run: |
          cd supabase/functions
          deno lint
      
      - name: Check formatting
        run: |
          cd supabase/functions
          deno fmt --check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - name: Run tests
        run: |
          cd supabase/functions
          deno task test
        env:
          # Provide mock environment variables for tests
          SUPABASE_URL: https://test.supabase.co
          SUPABASE_SERVICE_ROLE_KEY: test-key
          GITHUB_TOKEN: test-token
      
      - name: Generate coverage
        run: |
          cd supabase/functions
          deno task coverage
      
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: supabase/functions/coverage/lcov.info
          flags: edge-functions

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - name: Type check
        run: |
          cd supabase/functions
          deno check **/*.ts