name: Generate Social Cards

on:
  # Run daily to refresh cards
  schedule:
    - cron: '6 6 * * *'  # 6 AM UTC daily
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      repo_count:
        description: 'Number of repository cards to generate'
        required: false
        default: '3'
        type: string
  
  # Run when merging to main (optional)
  push:
    branches: [main]
    paths:
      - 'scripts/generate-social-cards.js'
      - 'src/components/social-cards/**'

jobs:
  generate-cards:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Strict timeout for 5-minute target
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ hashFiles('package-lock.json') }}
          restore-keys: playwright-browsers-
      
      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install chromium
      
      - name: Build application
        run: npm run build
      
      - name: Start preview server
        run: npm run preview &
        
      - name: Wait for server to be ready
        run: |
          timeout 30 bash -c 'until curl -f http://localhost:4173/; do sleep 1; done' || exit 1
      
      - name: Generate social cards
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          SUPABASE_TOKEN: ${{ secrets.SUPABASE_TOKEN }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          BASE_URL: 'http://localhost:4173'
          REPO_COUNT: ${{ github.event.inputs.repo_count || '3' }}
        run: node scripts/generate-social-cards.js
      
      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: social-card-logs
          path: |
            temp-social-cards/
            *.log
          retention-days: 7
      
      - name: Report success
        if: success()
        run: |
          echo "✅ Social cards generated successfully!"
          echo "🕐 Total runtime: ${{ job.duration || 'N/A' }}"
