name: Assign issues with .take

on:
  workflow_call:
  issue_comment:
    types:
      - created
      - edited

jobs:
  take-issue:
    name: Take issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    timeout-minutes: 10
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      
      - name: take an issue
        uses: bdougie/take-action@v1.6.1
        with:
          message: Thanks for taking this on! If you have not already, join the conversation in our [community discussions](https://github.com/orgs/open-sauced/discussions)
          issueCurrentlyAssignedMessage: Thanks for being interested in this issue. It looks like this ticket is already assigned to a contributor. Please communicate with the assigned contributor to confirm the status of the issue.
          token: ${{ steps.app-token.outputs.token }}
          blockingLabels: 👀 needs triage,🛑 blocked,🖍need-design,duplicate
          blockingLabelsMessage: The issue you are trying to assign yourself is blocked until it can be triaged or by another label on the issue.
