name: Update PR Activity

on:
  schedule:
    # Run every 6 hours on the 18th minute
    - cron: '18 */6 * * *'
  workflow_dispatch:
    inputs:
      repository_id:
        description: 'Repository ID to update (optional - updates all if not specified)'
        required: false
        type: string
      days:
        description: 'Number of days to look back for PR updates'
        required: false
        type: number
        default: 7

jobs:
  update-pr-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Trigger PR Activity Updates
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          INNGEST_EVENT_KEY: ${{ secrets.INNGEST_EVENT_KEY }}
          INNGEST_PRODUCTION_EVENT_KEY: ${{ secrets.INNGEST_PRODUCTION_EVENT_KEY }}
          API_ENDPOINT: ${{ secrets.API_ENDPOINT || 'https://contributor.info/api/queue-event' }}
          UPDATE_DELAY_MS: ${{ vars.UPDATE_DELAY_MS || '1000' }}
          REPOSITORY_ID: ${{ github.event.inputs.repository_id }}
          DAYS: ${{ github.event.inputs.days }}
        run: node scripts/data-sync/trigger-pr-activity-updates.js